#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shutil
import socket
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

HOME = Path.home()
VAULT = Path(os.environ.get("VAULT_DIR") or os.environ.get("OBSIDIAN_VAULT_DIR") or HOME / "Can")
STATE_DIR = HOME / ".local/state/control-plane-backup-readiness"
STATUS_PATH = STATE_DIR / "status.json"
MANIFEST_PATH = STATE_DIR / "manifest.md"


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def iso_now() -> str:
    return utc_now().isoformat().replace("+00:00", "Z")


def run(args: list[str], timeout: int = 8) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(args, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout)
    except Exception as exc:
        return subprocess.CompletedProcess(args, 1, "", str(exc))


def read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def write_json_atomic(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    tmp.replace(path)


def directory_size(path: Path) -> str:
    if not path.exists():
        return "missing"
    proc = run(["du", "-sh", str(path)], timeout=20)
    if proc.returncode == 0 and proc.stdout.strip():
        return proc.stdout.split()[0]
    if path.is_file():
        return str(path.stat().st_size)
    return "unknown"


def mtime_iso(path: Path) -> str:
    try:
        return datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc).isoformat().replace("+00:00", "Z")
    except OSError:
        return ""


def path_status(path: Path, *, secret_bearing: bool, restore_source: str, note: str) -> dict[str, Any]:
    return {
        "path": str(path),
        "exists": path.exists(),
        "kind": "dir" if path.is_dir() else "file" if path.is_file() else "missing",
        "size": directory_size(path),
        "mtime": mtime_iso(path),
        "secret_bearing": secret_bearing,
        "restore_source": restore_source,
        "note": note,
    }


def tool_status() -> dict[str, Any]:
    rclone_remotes: list[str] = []
    rclone = shutil.which("rclone")
    if rclone:
        proc = run(["rclone", "listremotes"], timeout=10)
        if proc.returncode == 0:
            rclone_remotes = [line.strip() for line in proc.stdout.splitlines() if line.strip()]

    return {
        "restic_installed": shutil.which("restic") is not None,
        "rclone_installed": rclone is not None,
        "rclone_remotes": rclone_remotes,
        "active_r2_remote": "r2:" in rclone_remotes,
        "disabled_r2_remote": any("r2" in remote.lower() or "vm-backup" in remote.lower() for remote in rclone_remotes)
        and "r2:" not in rclone_remotes,
    }


def collect_surfaces() -> list[dict[str, Any]]:
    return [
        path_status(
            VAULT,
            secret_bearing=False,
            restore_source="GitHub vault remote plus Obsidian Sync",
            note="Primary notes and migration docs. Backed up separately from raw workspace state.",
        ),
        path_status(
            HOME / ".local/state/vault-backup/status.json",
            secret_bearing=False,
            restore_source="Regenerated by vault-backup loop",
            note="Freshness signal for vault Git backup.",
        ),
        path_status(
            HOME / ".local/state/can-doctor/status.json",
            secret_bearing=False,
            restore_source="Regenerated by can-doctor",
            note="Current control-plane health surface.",
        ),
        path_status(
            HOME / ".local/state/can-doctor/tmux-inventory.json",
            secret_bearing=False,
            restore_source="Regenerated by can-doctor",
            note="Dynamic tmux service inventory.",
        ),
        path_status(
            HOME / ".local/bin",
            secret_bearing=False,
            restore_source="ai-dev bootstrap plus selected local scripts",
            note="Installed local operational scripts. Prefer restoring from template/repos.",
        ),
        path_status(
            HOME / ".local/state/github-repo-sweep/state.json",
            secret_bearing=False,
            restore_source="Regenerated by github-repo-sweep",
            note="Repo sweep freshness state.",
        ),
    ]


def build_payload() -> dict[str, Any]:
    tools = tool_status()
    surfaces = collect_surfaces()
    blockers: list[str] = []
    warnings: list[str] = []

    if not tools["restic_installed"]:
        blockers.append("restic is not installed")
    if not tools["active_r2_remote"]:
        blockers.append("active rclone remote r2: is not configured")

    for surface in surfaces:
        if not surface["exists"]:
            blockers.append(f"required surface missing: {surface['path']}")

    secret_surfaces = [surface for surface in surfaces if surface["secret_bearing"] and surface["exists"]]
    result = "blocked" if blockers else "ready"
    if not tools["restic_installed"] and not tools["active_r2_remote"]:
        next_action = "Install restic and configure scoped R2 credentials, then run an encrypted backup and restore test."
    elif not tools["restic_installed"]:
        next_action = "Install restic, then run an encrypted backup and restore test."
    elif not tools["active_r2_remote"]:
        next_action = "Configure active rclone remote r2: with scoped R2 credentials, then run an encrypted backup and restore test."
    elif blockers:
        next_action = "Resolve the missing required surfaces, then run an encrypted backup and restore test."
    else:
        next_action = "Run the first encrypted backup and restore drill before treating Hetzner as the main control plane."

    return {
        "schema": "control-plane-backup-readiness.v1",
        "updated_at": iso_now(),
        "host": socket.gethostname(),
        "result": result,
        "summary": {
            "surface_count": len(surfaces),
            "existing_surfaces": sum(1 for surface in surfaces if surface["exists"]),
            "secret_bearing_existing_surfaces": len(secret_surfaces),
            "blocker_count": len(blockers),
            "warning_count": len(warnings),
        },
        "tools": tools,
        "blockers": blockers,
        "warnings": warnings,
        "surfaces": surfaces,
        "next_action": next_action,
    }


def write_manifest(payload: dict[str, Any]) -> None:
    lines = [
        "# Control Plane Backup Readiness",
        "",
        f"- Updated: `{payload['updated_at']}`",
        f"- Host: `{payload['host']}`",
        f"- Result: `{payload['result']}`",
        f"- Surfaces: {payload['summary']['existing_surfaces']}/{payload['summary']['surface_count']} present",
        f"- Secret-bearing existing surfaces: {payload['summary']['secret_bearing_existing_surfaces']}",
        f"- Blockers: {payload['summary']['blocker_count']}",
        f"- Warnings: {payload['summary']['warning_count']}",
        "",
        "## Tool State",
        "",
        f"- restic installed: `{payload['tools']['restic_installed']}`",
        f"- rclone installed: `{payload['tools']['rclone_installed']}`",
        f"- active `r2:` remote: `{payload['tools']['active_r2_remote']}`",
        f"- configured remotes: `{', '.join(payload['tools']['rclone_remotes']) or 'none'}`",
        "",
    ]

    if payload["blockers"]:
        lines.extend(["## Blockers", ""])
        for blocker in payload["blockers"]:
            lines.append(f"- {blocker}")
        lines.append("")

    if payload["warnings"]:
        lines.extend(["## Warnings", ""])
        for warning in payload["warnings"]:
            lines.append(f"- {warning}")
        lines.append("")

    lines.extend(["## Surfaces", ""])
    for surface in payload["surfaces"]:
        secret = "secret-bearing" if surface["secret_bearing"] else "non-secret"
        exists = "present" if surface["exists"] else "missing"
        lines.append(f"- `{surface['path']}`: {exists}, {secret}, size `{surface['size']}`")
        lines.append(f"  - Restore source: {surface['restore_source']}")
        lines.append(f"  - Note: {surface['note']}")

    lines.extend(["", "## Next Action", "", payload["next_action"], ""])
    MANIFEST_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a no-upload control-plane backup readiness manifest")
    parser.add_argument("--json", action="store_true", help="print JSON payload")
    args = parser.parse_args()

    payload = build_payload()
    write_json_atomic(STATUS_PATH, payload)
    write_manifest(payload)

    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print("Control-plane backup readiness")
        print(f"Result: {payload['result']}")
        print(f"Surfaces: {payload['summary']['existing_surfaces']}/{payload['summary']['surface_count']} present")
        print(f"Blockers: {payload['summary']['blocker_count']}")
        print(f"Warnings: {payload['summary']['warning_count']}")
        print(f"Status: {STATUS_PATH}")
        print(f"Manifest: {MANIFEST_PATH}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
