#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shlex
import socket
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

HOME = Path.home()
STATE_DIR = HOME / ".local/state/hetzner-hardening-command-bundle"
STATUS_PATH = STATE_DIR / "status.json"
README_PATH = STATE_DIR / "README.md"
APPLY_PATH = STATE_DIR / "apply-hardening.sh"
ROLLBACK_PATH = STATE_DIR / "rollback-hardening.sh"
REMEDIATION_STATUS = HOME / ".local/state/hetzner-hardening-remediation/status.json"


def iso_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def write_json_atomic(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    tmp.replace(path)


def write_text_atomic(path: Path, text: str, *, mode: int = 0o600) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.chmod(mode)
    tmp.replace(path)
    path.chmod(mode)


def safe_md(value: Any) -> str:
    return str(value or "").replace("|", "\\|").replace("\n", " ").strip()


def shell_quote(value: str) -> str:
    return shlex.quote(value)


def target_host(target: str) -> str:
    return target.split("@", 1)[1] if "@" in target else target


def as_action_list(remediation: Any) -> list[dict[str, Any]]:
    if not isinstance(remediation, dict):
        return []
    actions = remediation.get("actions")
    return [item for item in actions if isinstance(item, dict)] if isinstance(actions, list) else []


def script_header(title: str, guard_var: str, guard_value: str) -> list[str]:
    return [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        f"# {title}",
        "# Generated by hetzner-hardening-command-bundle.",
        "# Review before use. No secrets are embedded.",
        "",
        f"if [[ \"${{{guard_var}:-}}\" != {shell_quote(guard_value)} ]]; then",
        f"  echo \"Refusing to run. Set {guard_var}={guard_value} after manual review.\" >&2",
        "  exit 64",
        "fi",
        "",
        "SSH_TARGET=\"${HETZNER_SSH_TARGET:-root@195.201.194.181}\"",
        "SSH_KEY=\"${HETZNER_SSH_KEY:-$HOME/.ssh/nomarh_hetzner}\"",
        "export SSH_TARGET SSH_KEY",
        "SSH_OPTS=(-i \"$SSH_KEY\" -o BatchMode=yes -o ConnectTimeout=8 -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new)",
        "",
        "run_remote() {",
        "  local command=$1",
        "  echo",
        "  echo \"==> remote: $command\"",
        "  ssh \"${SSH_OPTS[@]}\" \"$SSH_TARGET\" bash -lc \"$command\"",
        "}",
        "",
        "run_local() {",
        "  local command=$1",
        "  echo",
        "  echo \"==> local: $command\"",
        "  bash -lc \"$command\"",
        "}",
        "",
    ]


def render_apply_script(remediation: dict[str, Any]) -> str:
    target = str(remediation.get("target") or "root@195.201.194.181")
    host = target_host(target)
    key_path = str(remediation.get("source", {}).get("key_path") or "$HOME/.ssh/nomarh_hetzner")
    admin_user = str(remediation.get("admin_user") or "can")
    lines = script_header("Nomarh Hetzner hardening apply bundle", "NOMARH_HARDENING_APPLY", "reviewed")
    lines.extend(
        [
            f"# Current target from remediation: {target}",
            f"# Suggested admin user: {admin_user}",
            "# Keep an existing root SSH session open until non-root SSH and sudo verification pass.",
            "# Mailcow/Docker networking can bypass naive host firewall assumptions; verify after any firewall change.",
            "",
            "run_local 'hetzner-hardening-preflight --json >/tmp/nomarh-hetzner-hardening-before.json'",
        ]
    )

    for action in as_action_list(remediation):
        status = str(action.get("status", ""))
        if status != "pending":
            continue
        lines.extend(["", f"echo", f"echo '### {str(action.get('title', action.get('id', 'action')))}'"])
        if action.get("caution"):
            lines.append(f"echo {shell_quote('Caution: ' + str(action['caution']))}")
        for command in action.get("commands", []):
            lines.append(f"run_remote {shell_quote(str(command))}")

        for verify in action.get("verify", []):
            verify_text = str(verify)
            if verify_text.startswith("ssh "):
                verify_text = verify_text.replace(str(key_path), "$SSH_KEY").replace(f"{admin_user}@{host}", f"{admin_user}@{host}")
                lines.append(f"run_local {shell_quote(verify_text)}")
            elif verify_text.startswith("hetzner-") or verify_text.startswith("nomarh-") or verify_text.startswith("can-"):
                lines.append(f"run_local {shell_quote(verify_text)}")
            else:
                lines.append(f"run_remote {shell_quote(verify_text)}")

    lines.extend(
        [
            "",
            "run_local 'hetzner-hardening-preflight --json >/tmp/nomarh-hetzner-hardening-after.json'",
            "run_local 'hetzner-hardening-remediation --json >/tmp/nomarh-hetzner-remediation-after.json'",
            "run_local 'nomarh-ops --refresh --json >/tmp/nomarh-ops-after-hardening.json || true'",
            "echo",
            "echo 'Hardening bundle finished. Inspect /tmp/nomarh-hetzner-hardening-after.json and rerun nomarh-ops.'",
            "",
        ]
    )
    return "\n".join(lines)


def render_rollback_script(remediation: dict[str, Any]) -> str:
    admin_user = str(remediation.get("admin_user") or "can")
    lines = script_header("Nomarh Hetzner hardening rollback bundle", "NOMARH_HARDENING_ROLLBACK", "reviewed")
    lines.extend(
        [
            "# This rollback is intentionally narrow.",
            "# It disables UFW if firewall policy caused access/service problems.",
            "# It does not delete the admin user by default.",
            "",
            "run_remote 'ufw --force disable || true'",
            "run_remote 'ufw status verbose || true'",
            "",
            f"echo 'Optional manual rollback if sudoers policy for {admin_user} is wrong:'",
            f"echo {shell_quote('ssh \"$SSH_TARGET\" rm -f /etc/sudoers.d/90-nomarh-' + admin_user + ' && visudo -c')}",
            "",
            "run_local 'hetzner-hardening-preflight --json >/tmp/nomarh-hetzner-hardening-rollback.json || true'",
            "echo 'Rollback bundle finished. Inspect /tmp/nomarh-hetzner-hardening-rollback.json.'",
            "",
        ]
    )
    return "\n".join(lines)


def render_readme(payload: dict[str, Any]) -> str:
    lines = [
        "# Hetzner Hardening Command Bundle",
        "",
        "No remote changes are applied by the generator. The generated shell files are guarded and require explicit environment variables before they run.",
        "",
        f"- Updated: `{payload['updated_at']}`",
        f"- Result: `{payload['result']}`",
        f"- Target: `{safe_md(payload['target'])}`",
        f"- Source remediation result: `{safe_md(payload['source_result'])}`",
        f"- Pending actions: `{payload['summary']['pending_action_count']}`",
        f"- Apply script: `{payload['paths']['apply']}`",
        f"- Rollback script: `{payload['paths']['rollback']}`",
        "",
        "## Use",
        "",
        "Review scripts first:",
        "",
        "```bash",
        f"sed -n '1,260p' {shell_quote(payload['paths']['apply'])}",
        f"sed -n '1,220p' {shell_quote(payload['paths']['rollback'])}",
        "```",
        "",
        "Run only after keeping a root SSH session open and confirming the mail/firewall policy:",
        "",
        "```bash",
        f"NOMARH_HARDENING_APPLY=reviewed bash {shell_quote(payload['paths']['apply'])}",
        "```",
        "",
        "Emergency rollback for UFW policy only:",
        "",
        "```bash",
        f"NOMARH_HARDENING_ROLLBACK=reviewed bash {shell_quote(payload['paths']['rollback'])}",
        "```",
        "",
        "## Actions",
        "",
        "| ID | Status | Title |",
        "|---|---|---|",
    ]
    for item in payload["actions"]:
        lines.append(f"| `{safe_md(item.get('id'))}` | `{safe_md(item.get('status'))}` | {safe_md(item.get('title'))} |")
    if not payload["actions"]:
        lines.append("| none |  |  |")
    lines.append("")
    if payload["blockers"]:
        lines.extend(["## Blockers", ""])
        lines.extend(f"- {safe_md(item)}" for item in payload["blockers"])
        lines.append("")
    return "\n".join(lines)


def build_payload() -> dict[str, Any]:
    remediation = read_json(REMEDIATION_STATUS)
    blockers: list[str] = []
    if not isinstance(remediation, dict):
        blockers.append(f"remediation status missing or invalid: {REMEDIATION_STATUS}")
        remediation = {}
    if remediation.get("result") == "blocked":
        blockers.extend(str(item) for item in remediation.get("blockers", []) if item)

    actions = as_action_list(remediation)
    pending_actions = [item for item in actions if item.get("status") == "pending"]
    result = "blocked" if blockers else "pending" if pending_actions else "ready"
    payload = {
        "schema": "hetzner-hardening-command-bundle.v1",
        "updated_at": iso_now(),
        "host": socket.gethostname(),
        "result": result,
        "target": str(remediation.get("target") or ""),
        "source_result": str(remediation.get("result") or "missing"),
        "summary": {
            "action_count": len(actions),
            "pending_action_count": len(pending_actions),
            "blocker_count": len(blockers),
        },
        "blockers": blockers,
        "actions": actions,
        "paths": {
            "status": str(STATUS_PATH),
            "readme": str(README_PATH),
            "apply": str(APPLY_PATH),
            "rollback": str(ROLLBACK_PATH),
            "source_remediation": str(REMEDIATION_STATUS),
        },
        "guards": {
            "apply": "NOMARH_HARDENING_APPLY=reviewed",
            "rollback": "NOMARH_HARDENING_ROLLBACK=reviewed",
        },
    }
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate guarded shell bundles from Hetzner hardening remediation status")
    parser.add_argument("--json", action="store_true", help="print JSON payload")
    args = parser.parse_args()

    payload = build_payload()
    remediation = read_json(REMEDIATION_STATUS)
    remediation_dict = remediation if isinstance(remediation, dict) else {}
    write_text_atomic(APPLY_PATH, render_apply_script(remediation_dict), mode=0o600)
    write_text_atomic(ROLLBACK_PATH, render_rollback_script(remediation_dict), mode=0o600)
    write_text_atomic(README_PATH, render_readme(payload), mode=0o600)
    write_json_atomic(STATUS_PATH, payload)

    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print("Hetzner hardening command bundle")
        print(f"Result: {payload['result']}")
        print(f"Pending actions: {payload['summary']['pending_action_count']}")
        print(f"README: {README_PATH}")
    return 2 if payload["result"] == "blocked" else 0


if __name__ == "__main__":
    raise SystemExit(main())
